#!/usr/bin/env sh
#: Themed launcher

# Scheme name: base16 / Da One Black
# Scheme author: NNB (https://github.com/NNBnh)

bemenu-run --bottom --prompt '' \
           --tb '#000000' \
           --tf '#FFFFFF' \
           --nb '#000000' \
           --nf '#FFFFFF' \
           --hb '#6BB8FF' \
           --hf '#000000' \
           --ff '#FF9470'
