#!/usr/bin/env sh
#: Themed launcher

# Scheme name: base16 / Atelier Seaside
# Scheme author: Bram de Haan (http://atelierbramdehaan.nl)

bemenu-run --bottom --prompt '' \
           --tb '#131513' \
           --tf '#8ca68c' \
           --nb '#131513' \
           --nf '#8ca68c' \
           --hb '#3d62f5' \
           --hf '#131513' \
           --ff '#98981b'
