#!/usr/bin/env sh
#: You shouldn't need this. I once thought I needed it, but I didn't.

# do it this way so we continue after failures
for file in `ls /nix/store/*.lock`
do
    nix-store --delete $file
done
