#!/bin/bash

dotfileDir="~/dotWombat"

targetName () {
  echo ${1/#./}
}

do_sync () {
  echo "sync not implemented"
}

do_add () {
  file=$1
  
  if [ -z "${file}" ]
  then
    do_help
    exit 3
  fi

  targetName ${file}
  linkTarget=${dotfileDir}/`targetName ${file}`
  
  if [ -L "${file}" ]
  then
    target=`readlink ${file}`
    if [ ${target} -ef ${linkTarget} ]
    then
      echo "${file} is already in ${dotfileDir} and is correctly linked"
      echo 1
    else
      echo "${file} is already a link, but it's not correct"
      echo "${file} links to ${target} instead of ${linkTarget}"
      exit 3
    fi
  fi

  if [ -f "${file}" ]
  then
    echo "${file} is a regular file"
    echo "TODO: Check to see if it's in dotWombat"
    echo "TODO: Create the link"
    exit 3
  fi

  echo "add not implemented"
  echo mv ${file} ${linkTarget}
  echo ln -s ${file} ${linkTarget}
}

do_help () {
        echo "Usage: dotWombat [add <path>|sync]" >&2
        exit 3
}

case "$1" in
  add)
        do_add $2
        exit $?
        ;;
  sync)
        do_sync
        exit $?
        ;;
  *)
	do_help
        ;;
esac
