#!/bin/bash

DOTFILE_DIR=~/dotWombat
CONFIG_FILE=${DOTFILE_DIR}/config

function targetPath {
  echo ${DOTFILE_DIR}/$1
}

function setupLink {
  if [ -e $1 ]; then
    if [ -h $1 ]; then
      if [ -e $2 ]; then
        TARGET=`readlink $1`
	if [ "${TARGET}" = "$2" ]; then
	  echo "$1 is properly linked"
	else
	  echo "ERROR: $1 links to ${TARGET} instead of $2"
	fi
      else
        echo "$1 is a symbolic link, but $2 does not exist"
      fi
    else
      if [ -e $2 ]; then
        echo "ERROR: $2 exists, but $1 is not a symbolic link"
      else
        echo "Moving $1 to $2 and creating link"
        mv $1 $2
        ln -s $2 $1
      fi
    fi
  else
    if [ -e $2 ]; then
      echo "Creating link from $1 to $2"
      ln -s $2 $1
    else
      echo "ERROR: $2 does not exist"
    fi
  fi
}

while read DOTFILE
  do
    # echo "Processing ${DOTFILE}"
    LINK_NAME=~/${DOTFILE}
    TARGET=`targetPath ${DOTFILE}`
    setupLink ${LINK_NAME} ${TARGET}
  done < "${CONFIG_FILE}"
