#!/usr/bin/env sh
#: Creates this file (README.md).

echo '# bin'
echo ''
echo 'A collection of useful scripts.'
echo 'Each script is summarised below.'
echo ''

for file in `find . -name LICENSE -prune \
                 -o -name README.md -prune \
		 -o -name '.git*' -prune \
		 -o -name '*~' -prune \
		 -o -name '*.mustache' -prune \
		 -o -name '.textadept_session' -prune \
		 -o -type f -print \
		 | sort`
do
  file=$(echo $file | sed 's_.*/__')
  echo "## [$file](https://github.com/mhwombat/bin/blob/master/$file)"
  echo ""
  grep '^#:' $file | sed 's/^#: //; s/^#://'
  echo ''
done
