#!/usr/bin/env sh
#: Set up a directory for Nix+Hskell development.


cat << EOF > default.nix
let
  pkgs = import <nixpkgs> { };
in
  pkgs.haskellPackages.developPackage {
    root = ./.;
    modifier = drv:
      pkgs.haskell.lib.addBuildTools drv (with pkgs.haskellPackages;
        [
          cabal-install
        ]);
  }
EOF

cat << EOF > .envrc
use nix
EOF
