#!/usr/bin/env sh
#: `note [MESSAGE]` adds a message to my personal log.
#: If MESSAGE is omitted, opens today's log for editing.

function writeToFile {
  FILE=$1
  MESSAGE=$2

  if [ -s "${FILE}" ]; then
     # file is exists and is nonempty
     echo "Appending to ${FILE}"
     echo -en "\n${MESSAGE}" >> ${FILE}
  else
     # File is empty or does not exist
     echo "Creating ${FILE}"
     echo "${MESSAGE}" > ${FILE}
  fi
}

MESSAGE=$*

LOGDIR=~/github/notes

LOGFILE=$(date "+%Y-%m-%d").md


if [ $# == 0 ]; then
  nano ${LOGDIR}/${LOGFILE}
else
  writeToFile ${LOGDIR}/${LOGFILE} ${MESSAGE}
fi
