#!/usr/bin/env sh
#: Generate a preview of a colour scheme.
THEME_DIR=~/dotWombat/themes
PREVIEW_DIR=${THEME_DIR}/previews
TEMPLATE_FILE=${THEME_DIR}/html.mustache

mkdir -p ${PREVIEW_DIR}

for file in $(ls ${THEME_DIR}/*.json); do
    theme=$(basename -s .json $file)
    mustache $file ${TEMPLATE_FILE} > ${PREVIEW_DIR}/${theme}.html
done

