#!/usr/bin/env sh
#: Change colour scheme for supported apps.

THEMEDIR=~/dotWombat/themes

# foot
FOOT_THEME_DIR=~/dotWombat/.config/foot
mustache ${THEMEDIR}/$1.json ${FOOT_THEME_DIR}/foot.mustache > ${FOOT_THEME_DIR}/foot.ini

# alacritty
ALACRITTY_THEME_DIR=~/dotWombat/.config/alacritty
mustache ${THEMEDIR}/$1.json ${ALACRITTY_THEME_DIR}/alacritty.yml.mustache > ${ALACRITTY_THEME_DIR}/alacritty.yml

# emacs
EMACS_THEME_DIR=~/dotWombat/.config/emacs/amy/themes
mustache ${THEMEDIR}/$1.json ${EMACS_THEME_DIR}/base16-current-theme.mustache > ${EMACS_THEME_DIR}/base16-current-theme.el
