#!/usr/bin/env sh
#: A quick script to load all of the Haskell source files
#: and configuration files in the current project
#: into emacs.

dir=`pwd | sed 's@.*/@@'`
files=`ls notes *.nix *.cabal README.md CHANGELOG.md 2>/dev/null`

files="${files} `find . -not \( -name dist-newstyle -prune \) -name '*.hs' -or -name '*.lhs' | sort`"
# echo ${files}
# emacs --title "${dir} : emacs" ${files} &
we --force --nosession --userhome $XDG_CONFIG_HOME/textadept ${files} &
