#!/usr/bin/env sh
#: A quick script to load all of the Haskell source files
#: and configuration files in the current Stack project
#: into emacs.

dir=`pwd | sed 's@.*/@@'`
files=`ls *.yaml ChangeLog.md`

files="${files} `find app* -name '*.hs' -or -name '*.lhs' | sort`"

if [ -d "src" ]; then
  files="${files} `find src -name '*.hs' -or -name '*.lhs' | sort`"
fi

if [ -d "test" ]; then
  files="${files} `find test -name '*.hs' -or -name '*.lhs' | sort`"
fi

#gedit ${files} &
#cream ${files} &
#gvim ${files} &
emacs --title "${dir} : emacs" ${files} &

