#!/usr/bin/env sh
#: A quick script to load all of the Haskell source files
#: and configuration files in the current project
#: into emacs.

dir=`pwd | sed 's@.*/@@'`
files=`ls notes *.nix *.cabal CHANGELOG.md`

files="${files} `find . -not \( -name dist-newstyle -prune \) -name '*.hs' -or -name '*.lhs' | sort`"
# echo ${files}
emacs --title "${dir} : emacs" ${files} &

